version: '3.1'

services:
  db:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword

    volumes:
      - ~/mongodb/database:/data/db
    ports:
      - '27017:27017'
    restart: always

  discord-bot:
    build: .
    ports:
      - '5000:5000'
    links:
      - db
    restart: on-failure
